// export command — archive a run's evidence into one inspectable JSON bundle (issue #159).
//
// The read-only, evidence-preserving companion to `realm run purge` (#107): before (or instead of)
// permanently deleting a run's artifacts, `realm run export <id>` writes them into a single,
// self-contained, human-readable JSON file an operator can `cat`/`grep`/`git add`/attach to a bug
// report. Read-only and lock-free by construction — it only ever calls each store's existing PUBLIC
// READ methods (`runStore.get`, `failedAttemptStore.read`, `traceBufferStore.readAllForRun`); no
// filename layout is hard-coded here, and nothing is written to `runsDir`, unlinked, or locked.
//
// Works on ANY run, not just terminal ones — export's highest-value use is handing off a *stuck*
// (non-terminal) run for debugging, which a terminal-only gate would forbid, and read-only means
// there is no safety reason to restrict it. A non-terminal run gets a best-effort-snapshot warning
// instead (its artifacts are read at slightly different instants and may be mid-flight); a terminal
// run needs no warning, since nothing changes post-seal.
//
// The bundle deliberately excludes the idempotency-key pointer (`keys/<hash>.json`): that file is a
// rebuildable hash→run INDEX (regenerated by `reconcile`), not run evidence, and the key it maps is
// already present on the run record itself (`run.idempotency_key`).
import { existsSync, statSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { join, resolve, sep } from 'node:path';
import { Command } from 'commander';
import type {
  RunRecord,
  RunStore,
  FailedAttemptRecord,
  TraceBufferStore,
  SealedArtifact,
} from '@sensigo/realm';
import { WorkflowError, isTerminalPhase, FsIoError } from '@sensigo/realm';

/** Fixed redaction marker (issue #197 PR-2, design §6) — replaces every `nonce` value belonging
 *  to a step currently in `in_progress_steps` on a NON-terminal export (the claimant-nonce
 *  disclosure channel: `get_run_state` never leaks it, but an export of a live run otherwise
 *  would). Terminal exports are always verbatim — nothing is still claimable once a run is done. */
const REDACTED_LIVE_CLAIM_NONCE = '[redacted-live-claim]';

/** One artifact `buildExportBundle` could not read (issue #186) — never silently omitted. */
export interface ExportArtifactError {
  /** A human label for the artifact — the STORE owns the actual on-disk path/filename; the
   *  command never reconstructs one, matching this file's own no-filename-layout discipline. */
  artifact: string;
  /** The errno/FsIoError code, or `'UNKNOWN'` if the thrown value carried none. */
  code: string;
  message: string;
}

export interface ExportBundle {
  /**
   * Bumped 1 → 2 (issue #186): a v1 bundle predates the `complete`/`artifact_errors` fields, so a
   * v1 bundle's completeness is UNKNOWN to a reader — it was written back when export was
   * all-or-nothing (any read failure meant no bundle at all), so v1's mere existence was itself a
   * (weaker) completeness signal, but nothing in a v1 bundle states it explicitly. v2 always
   * states it explicitly via `complete`. Bumped 2 → 3 (issue #197 PR-2): adds `sealed`.
   */
  realm_export_version: 3;
  /** ISO-8601, stamped by the CLI at assembly time. */
  exported_at: string;
  /** The full RunRecord — steps, evidence, skip_details, claims, etc. */
  run: RunRecord;
  /** Parsed failed-attempt records; `[]` if none were ever recorded for this run OR if the sidecar
   *  read failed (see `artifact_errors` — the empty array does not by itself mean "none recorded"
   *  in that case; check `complete` first). */
  attempts: FailedAttemptRecord[];
  /** True if the run hit the failed-attempt sidecar's 256KB ceiling — later attempts were dropped
   *  at write time (append-and-stop), so `attempts` is NOT exhaustive. Independent of `complete`:
   *  a sidecar can be BOTH fully readable AND capped (a known, positively-characterized
   *  truncation) — that is a different signal from a read that failed outright. */
  attempts_capped: boolean;
  /** `{ <stepId>: [...] }` — every buffered/WAL entry for the run, across all steps; `{}` if none
   *  OR if the WAL read failed (see `artifact_errors` — check `complete` first). On a NON-terminal
   *  export, any `nonce` field on a line belonging to a step in `run.in_progress_steps` is
   *  replaced with `"[redacted-live-claim]"` (issue #197 PR-2, design §6 — the claimant-nonce
   *  disclosure channel); terminal exports are verbatim. */
  wal: Record<string, unknown[]>;
  /**
   * Every sealed trace artifact for the run, keyed by stepId (issue #197 PR-2, the `seal` rung).
   * `null` = the configured trace-buffer store does NOT declare `seal` (incapability — there is
   * nothing to enumerate, ever, on this store). `{}` = the store DOES declare `seal` but this run
   * genuinely has none (capable, empty). Same redaction rule as `wal` applies to sealed lines
   * belonging to an in-progress step on a non-terminal export.
   */
  sealed: Record<string, SealedArtifact[]> | null;
  /**
   * False iff any artifact below (`attempts`/`wal`/`sealed`) could not be read (issue #186) — a
   * real I/O failure, not a genuine ENOENT absence (an absent artifact is legitimately `[]`/`{}`
   * and `complete: true`). The bundle NEVER lies by omission: every readable artifact is still
   * written, and the run record itself is always present when `complete` is `false` (a run-record
   * read failure means no bundle is written at all — see `buildExportBundle`).
   */
  complete: boolean;
  /** The artifacts that failed to read; always `[]` when `complete` is `true`. */
  artifact_errors: ExportArtifactError[];
}

export interface ExportRunResult {
  bundle: ExportBundle;
  /**
   * Set (to the warning text) when the run was non-terminal at export time — a best-effort
   * snapshot, since its artifacts were read at slightly different instants and it may still be
   * mid-flight. `undefined` for a terminal run (nothing to warn about — nothing changes post-seal).
   * Returned as data, not printed here, so this stays assertable without a console spy (mirrors the
   * `cleanup`/`purge` precedent of testing exported logic, not console output).
   */
  warning: string | undefined;
}

export interface ExportStores {
  runStore: Pick<RunStore, 'get'>;
  failedAttemptStore: {
    read(runId: string): Promise<{ records: FailedAttemptRecord[]; capped: boolean }>;
  };
  /**
   * `listSealedForRun` (issue #197 PR-2) is OPTIONAL on the Pick, not required — its mere
   * presence as a function is this command's own incapability signal (`sealed: null` when
   * absent), deliberately NOT the store-layer's `storeDeclaresSeal` predicate: that predicate
   * additionally requires the full fenced-trio surface, which would force this deliberately
   * minimal, read-only Pick to widen far beyond what export actually calls. The construction-time
   * `validateTraceCapabilities` gate (server.ts) is what keeps a real store's declaration
   * internally consistent; this command only ever needs to know whether the ONE method it calls
   * exists.
   */
  traceBufferStore: Pick<TraceBufferStore, 'readAllForRun' | 'listSealedForRun'>;
}

/** Extracts an errno/FsIoError code from a thrown value; `'UNKNOWN'` if it carries none. */
function errnoCodeOf(err: unknown): string {
  if (err instanceof FsIoError) return err.code;
  const code = (err as { code?: unknown } | undefined)?.code;
  return typeof code === 'string' ? code : 'UNKNOWN';
}

/** True iff `line` is a plain object carrying a genuine (non-`undefined`) `nonce` value — the
 *  WAL's raw parsed-line shape is `unknown` (readAllForRun's own contract), so this is a runtime
 *  narrowing check, never a cast. A bare line (no `nonce` at all) is untouched — there is nothing
 *  to redact for it. */
function hasNonce(line: unknown): line is { nonce: string } {
  return (
    typeof line === 'object' &&
    line !== null &&
    'nonce' in line &&
    (line as { nonce?: unknown }).nonce !== undefined
  );
}

/**
 * Redacts every genuine `nonce` value on a WAL line or sealed-artifact line belonging to a step
 * in `liveSteps` (issue #197 PR-2, design §6) — the claimant-nonce disclosure channel a
 * non-terminal export would otherwise open (a run's own `ClaimRecord` never persists its nonce,
 * so this stateless step-liveness proxy is the only signal available). Steps NOT in `liveSteps`
 * (settled, or the run has none) pass through completely untouched — including bare lines, which
 * have no `nonce` to redact in the first place.
 */
function redactLiveClaimNonces(
  wal: Record<string, unknown[]>,
  sealed: Record<string, SealedArtifact[]> | null,
  inProgressSteps: readonly string[],
): { wal: Record<string, unknown[]>; sealed: Record<string, SealedArtifact[]> | null } {
  const liveSteps = new Set(inProgressSteps);
  if (liveSteps.size === 0) return { wal, sealed };

  const redactedWal: Record<string, unknown[]> = {};
  for (const [stepId, lines] of Object.entries(wal)) {
    redactedWal[stepId] = liveSteps.has(stepId)
      ? lines.map((line) => (hasNonce(line) ? { ...line, nonce: REDACTED_LIVE_CLAIM_NONCE } : line))
      : lines;
  }

  const redactedSealed: Record<string, SealedArtifact[]> | null =
    sealed === null
      ? null
      : Object.fromEntries(
          Object.entries(sealed).map(([stepId, artifacts]) => [
            stepId,
            liveSteps.has(stepId)
              ? artifacts.map((artifact) => ({
                  ...artifact,
                  lines: artifact.lines.map((line) =>
                    line.nonce !== undefined ? { ...line, nonce: REDACTED_LIVE_CLAIM_NONCE } : line,
                  ),
                }))
              : artifacts,
          ]),
        );

  return { wal: redactedWal, sealed: redactedSealed };
}

/**
 * Assembles the export bundle for `runId` from each store's existing read methods — never writes,
 * never locks, never touches `runsDir`. Throws `STATE_RUN_NOT_FOUND` (propagated from
 * `runStore.get`) for a nonexistent run; the CLI action maps that to an error message + exit(1).
 *
 * issue #186 — graceful degradation, never all-or-nothing: `run` is the bundle's core, so a
 * failure reading IT propagates (there is genuinely nothing to hand off — no bundle at all). But
 * `attempts` and `wal` are each read in their OWN try/catch: a real I/O failure on either (post
 * #183, `failedAttemptStore.read`/`traceBufferStore.readAllForRun` throw on a genuine I/O error,
 * not just a benign ENOENT-absence, which still legitimately yields `[]`/`{}`) substitutes the
 * empty value, records the failure in `artifact_errors`, and the OTHER artifact is still
 * attempted — the bundle self-describes its own incompleteness via `complete` instead of
 * disappearing entirely.
 */
export async function buildExportBundle(
  runId: string,
  stores: ExportStores,
  now: Date = new Date(),
): Promise<ExportRunResult> {
  const run = await stores.runStore.get(runId);

  const artifactErrors: ExportArtifactError[] = [];

  let attempts: FailedAttemptRecord[] = [];
  let attemptsCapped = false;
  try {
    const result = await stores.failedAttemptStore.read(runId);
    attempts = result.records;
    attemptsCapped = result.capped;
  } catch (err) {
    artifactErrors.push({
      artifact: 'failed-attempt sidecar',
      code: errnoCodeOf(err),
      message: err instanceof Error ? err.message : String(err),
    });
  }

  let wal: Record<string, unknown[]> = {};
  try {
    wal = await stores.traceBufferStore.readAllForRun(runId);
  } catch (err) {
    artifactErrors.push({
      artifact: 'trace-buffer WAL',
      code: errnoCodeOf(err),
      message: err instanceof Error ? err.message : String(err),
    });
  }

  // issue #197 PR-2: `listSealedForRun` is OPTIONAL on the (deliberately minimal) Pick above —
  // its mere presence as a function is this command's own incapability signal. `null` (never
  // touched) = incapable; `{}` (the loop below simply finds nothing to push) = capable, empty; a
  // read failure defaults to `{}` too (matching `attempts`/`wal`'s own on-failure convention) —
  // `complete: false` + `artifact_errors` is what actually signals "the read failed", not the
  // shape of `sealed` itself.
  let sealed: Record<string, SealedArtifact[]> | null = null;
  if (typeof stores.traceBufferStore.listSealedForRun === 'function') {
    sealed = {};
    try {
      const artifacts = await stores.traceBufferStore.listSealedForRun(runId);
      for (const artifact of artifacts) {
        (sealed[artifact.step_id] ??= []).push(artifact);
      }
    } catch (err) {
      sealed = {};
      artifactErrors.push({
        artifact: 'sealed trace artifacts',
        code: errnoCodeOf(err),
        message: err instanceof Error ? err.message : String(err),
      });
    }
  }

  // issue #197 PR-2 (design §6, the implementation pin): claims never persist their nonce (only
  // the stateless step-liveness proxy is available), so a NON-terminal export redacts every
  // `nonce` on a line belonging to a step CURRENTLY in `run.in_progress_steps` — conservative
  // over-redaction of a dead foreign nonce on a re-driven live step is accepted (verbatim once
  // the run goes terminal). A terminal export is always verbatim — nothing is still claimable.
  const nonTerminal = !isTerminalPhase(run.run_phase);
  const { wal: finalWal, sealed: finalSealed } = nonTerminal
    ? redactLiveClaimNonces(wal, sealed, run.in_progress_steps)
    : { wal, sealed };

  const bundle: ExportBundle = {
    realm_export_version: 3,
    exported_at: now.toISOString(),
    run,
    attempts,
    attempts_capped: attemptsCapped,
    wal: finalWal,
    sealed: finalSealed,
    complete: artifactErrors.length === 0,
    artifact_errors: artifactErrors,
  };

  const warning = nonTerminal
    ? `best-effort snapshot: run '${runId}' is still ${run.run_phase}; its artifacts are read at ` +
      `slightly different instants and may be mid-flight`
    : undefined;

  return { bundle, warning };
}

export interface ResolveExportPathOptions {
  runId: string;
  /** The raw `--out` flag value, if given. */
  out?: string | undefined;
  /** `runStore.runsDirPath` — the export target must never resolve inside it. */
  runsDir: string;
}

/**
 * Resolves the final, absolute output path for an export, or throws (never writes anything
 * itself — purely a path decision). Resolution order:
 *  1. No `--out` → `<cwd>/<runId>.realm.json`.
 *  2. `--out` names an EXISTING DIRECTORY → `<out>/<runId>.realm.json`.
 *  3. Otherwise `--out` is treated as the literal file path.
 * Then refuses (throws `WorkflowError`, code `VALIDATION_INPUT_SCHEMA`) if the resolved path is:
 *  - inside `runsDir` — export must never write into the store's own directory (would confuse
 *    `list()`'s naive `.json`-suffix filter, and clutters the space `gc`/`purge` manage); or
 *  - an already-existing file — export never clobbers; the operator picks a different `--out`.
 */
export function resolveExportPath(opts: ResolveExportPathOptions): string {
  let target: string;
  if (opts.out === undefined) {
    target = join(process.cwd(), `${opts.runId}.realm.json`);
  } else if (existsSync(opts.out) && statSync(opts.out).isDirectory()) {
    target = join(opts.out, `${opts.runId}.realm.json`);
  } else {
    target = opts.out;
  }

  const resolvedTarget = resolve(target);
  const resolvedRunsDir = resolve(opts.runsDir);
  if (resolvedTarget === resolvedRunsDir || resolvedTarget.startsWith(resolvedRunsDir + sep)) {
    throw new WorkflowError(
      `Refusing to write the export inside runsDir ('${resolvedRunsDir}') — choose a different --out.`,
      {
        code: 'VALIDATION_INPUT_SCHEMA',
        category: 'VALIDATION',
        agentAction: 'provide_input',
        retryable: false,
      },
    );
  }

  if (existsSync(resolvedTarget)) {
    throw new WorkflowError(
      `Refusing to overwrite existing file '${resolvedTarget}'. Choose a different --out.`,
      {
        code: 'VALIDATION_INPUT_SCHEMA',
        category: 'VALIDATION',
        agentAction: 'provide_input',
        retryable: false,
      },
    );
  }

  return resolvedTarget;
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}

export const exportCommand = new Command('export')
  .description(
    "Archive a run's evidence (record + failed-attempt sidecar + WAL traces) into one inspectable JSON bundle — read-only",
  )
  .argument('<run-id>', 'ID of the run to export')
  .option('--out <path>', 'Output file or directory (default: ./<run-id>.realm.json)')
  .action(async (runId: string, opts: { out?: string }) => {
    const { JsonFileStore, FailedAttemptStore } = await import('@sensigo/realm');
    const { JsonTraceBufferStore } = await import('@sensigo/realm-mcp');
    const runStore = new JsonFileStore();
    const runsDir = runStore.runsDirPath;
    const failedAttemptStore = new FailedAttemptStore(runsDir);
    const traceBufferStore = new JsonTraceBufferStore(runsDir);

    try {
      const { bundle, warning } = await buildExportBundle(runId, {
        runStore,
        failedAttemptStore,
        traceBufferStore,
      });

      if (warning !== undefined) {
        console.warn(`⚠ ${warning}`);
      }
      if (bundle.attempts_capped) {
        console.warn(
          '⚠ failed-attempt log was truncated at its size ceiling — the exported attempts list is not exhaustive.',
        );
      }

      const target = resolveExportPath({ runId, out: opts.out, runsDir });
      const json = JSON.stringify(bundle, null, 2);
      await writeFile(target, json, 'utf8');

      // issue #186: an incomplete bundle is still written (for recovery) but never reported as a
      // plain success — the exit code carries the signal for CI/scripts, and the operator sees
      // exactly which artifact(s) failed and why. No --allow-incomplete flag: honesty here is not
      // opt-in.
      if (!bundle.complete) {
        console.error(
          `⚠ INCOMPLETE export: ${bundle.artifact_errors.length} artifact(s) could not be read`,
        );
        for (const e of bundle.artifact_errors) {
          console.error(`  ✗ ${e.artifact} (${e.code}): ${e.message}`);
        }
        console.error(
          `The bundle was still written to '${target}' — inspect it for what could be recovered.`,
        );
        process.exit(1);
      }

      const walStepCount = Object.keys(bundle.wal).length;
      // issue #197 PR-2: sealed is null (incapable store) vs {} (capable, empty) vs non-empty —
      // report all three distinctly rather than collapsing null/empty into the same "0".
      const sealedSummary =
        bundle.sealed === null
          ? 'n/a (store does not declare seal)'
          : `${Object.values(bundle.sealed).reduce((n, arr) => n + arr.length, 0)}`;
      console.log(
        `Exported run '${runId}' to '${target}' (${formatBytes(Buffer.byteLength(json))}).\n` +
          `  phase: ${bundle.run.run_phase}, attempts: ${bundle.attempts.length}, WAL steps: ${walStepCount}, sealed artifacts: ${sealedSummary}`,
      );
    } catch (err) {
      console.error(err instanceof Error ? err.message : String(err));
      process.exit(1);
    }
  });
