// export command — archive a run's evidence into one inspectable JSON bundle (issue #159).
//
// The read-only, evidence-preserving companion to `realm run purge` (#107): before (or instead of)
// permanently deleting a run's artifacts, `realm run export <id>` writes them into a single,
// self-contained, human-readable JSON file an operator can `cat`/`grep`/`git add`/attach to a bug
// report. Read-only and lock-free by construction — it only ever calls each store's existing PUBLIC
// READ methods (`runStore.get`, `failedAttemptStore.read`, `traceBufferStore.readAllForRun`); no
// filename layout is hard-coded here, and nothing is written to `runsDir`, unlinked, or locked.
//
// Works on ANY run, not just terminal ones — export's highest-value use is handing off a *stuck*
// (non-terminal) run for debugging, which a terminal-only gate would forbid, and read-only means
// there is no safety reason to restrict it. A non-terminal run gets a best-effort-snapshot warning
// instead (its artifacts are read at slightly different instants and may be mid-flight); a terminal
// run needs no warning, since nothing changes post-seal.
//
// The bundle deliberately excludes the idempotency-key pointer (`keys/<hash>.json`): that file is a
// rebuildable hash→run INDEX (regenerated by `reconcile`), not run evidence, and the key it maps is
// already present on the run record itself (`run.idempotency_key`).
import { existsSync, statSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { join, resolve, sep } from 'node:path';
import { Command } from 'commander';
import type { RunRecord, RunStore, FailedAttemptRecord, TraceBufferStore } from '@sensigo/realm';
import { WorkflowError, isTerminalPhase } from '@sensigo/realm';

export interface ExportBundle {
  realm_export_version: 1;
  /** ISO-8601, stamped by the CLI at assembly time. */
  exported_at: string;
  /** The full RunRecord — steps, evidence, skip_details, claims, etc. */
  run: RunRecord;
  /** Parsed failed-attempt records; `[]` if none were ever recorded for this run. */
  attempts: FailedAttemptRecord[];
  /** `{ <stepId>: [...] }` — every buffered/WAL entry for the run, across all steps; `{}` if none. */
  wal: Record<string, unknown[]>;
}

export interface ExportRunResult {
  bundle: ExportBundle;
  /**
   * Set (to the warning text) when the run was non-terminal at export time — a best-effort
   * snapshot, since its artifacts were read at slightly different instants and it may still be
   * mid-flight. `undefined` for a terminal run (nothing to warn about — nothing changes post-seal).
   * Returned as data, not printed here, so this stays assertable without a console spy (mirrors the
   * `cleanup`/`purge` precedent of testing exported logic, not console output).
   */
  warning: string | undefined;
}

export interface ExportStores {
  runStore: Pick<RunStore, 'get'>;
  failedAttemptStore: { read(runId: string): Promise<{ records: FailedAttemptRecord[] }> };
  traceBufferStore: Pick<TraceBufferStore, 'readAllForRun'>;
}

/**
 * Assembles the export bundle for `runId` from each store's existing read methods — never writes,
 * never locks, never touches `runsDir`. Throws `STATE_RUN_NOT_FOUND` (propagated from
 * `runStore.get`) for a nonexistent run; the CLI action maps that to an error message + exit(1).
 */
export async function buildExportBundle(
  runId: string,
  stores: ExportStores,
  now: Date = new Date(),
): Promise<ExportRunResult> {
  const run = await stores.runStore.get(runId);
  const { records: attempts } = await stores.failedAttemptStore.read(runId);
  const wal = await stores.traceBufferStore.readAllForRun(runId);

  const bundle: ExportBundle = {
    realm_export_version: 1,
    exported_at: now.toISOString(),
    run,
    attempts,
    wal,
  };

  const warning = !isTerminalPhase(run.run_phase)
    ? `best-effort snapshot: run '${runId}' is still ${run.run_phase}; its artifacts are read at ` +
      `slightly different instants and may be mid-flight`
    : undefined;

  return { bundle, warning };
}

export interface ResolveExportPathOptions {
  runId: string;
  /** The raw `--out` flag value, if given. */
  out?: string | undefined;
  /** `runStore.runsDirPath` — the export target must never resolve inside it. */
  runsDir: string;
}

/**
 * Resolves the final, absolute output path for an export, or throws (never writes anything
 * itself — purely a path decision). Resolution order:
 *  1. No `--out` → `<cwd>/<runId>.realm.json`.
 *  2. `--out` names an EXISTING DIRECTORY → `<out>/<runId>.realm.json`.
 *  3. Otherwise `--out` is treated as the literal file path.
 * Then refuses (throws `WorkflowError`, code `VALIDATION_INPUT_SCHEMA`) if the resolved path is:
 *  - inside `runsDir` — export must never write into the store's own directory (would confuse
 *    `list()`'s naive `.json`-suffix filter, and clutters the space `gc`/`purge` manage); or
 *  - an already-existing file — export never clobbers; the operator picks a different `--out`.
 */
export function resolveExportPath(opts: ResolveExportPathOptions): string {
  let target: string;
  if (opts.out === undefined) {
    target = join(process.cwd(), `${opts.runId}.realm.json`);
  } else if (existsSync(opts.out) && statSync(opts.out).isDirectory()) {
    target = join(opts.out, `${opts.runId}.realm.json`);
  } else {
    target = opts.out;
  }

  const resolvedTarget = resolve(target);
  const resolvedRunsDir = resolve(opts.runsDir);
  if (resolvedTarget === resolvedRunsDir || resolvedTarget.startsWith(resolvedRunsDir + sep)) {
    throw new WorkflowError(
      `Refusing to write the export inside runsDir ('${resolvedRunsDir}') — choose a different --out.`,
      {
        code: 'VALIDATION_INPUT_SCHEMA',
        category: 'VALIDATION',
        agentAction: 'provide_input',
        retryable: false,
      },
    );
  }

  if (existsSync(resolvedTarget)) {
    throw new WorkflowError(
      `Refusing to overwrite existing file '${resolvedTarget}'. Choose a different --out.`,
      {
        code: 'VALIDATION_INPUT_SCHEMA',
        category: 'VALIDATION',
        agentAction: 'provide_input',
        retryable: false,
      },
    );
  }

  return resolvedTarget;
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}

export const exportCommand = new Command('export')
  .description(
    "Archive a run's evidence (record + failed-attempt sidecar + WAL traces) into one inspectable JSON bundle — read-only",
  )
  .argument('<run-id>', 'ID of the run to export')
  .option('--out <path>', 'Output file or directory (default: ./<run-id>.realm.json)')
  .action(async (runId: string, opts: { out?: string }) => {
    const { JsonFileStore, FailedAttemptStore } = await import('@sensigo/realm');
    const { JsonTraceBufferStore } = await import('@sensigo/realm-mcp');
    const runStore = new JsonFileStore();
    const runsDir = runStore.runsDirPath;
    const failedAttemptStore = new FailedAttemptStore(runsDir);
    const traceBufferStore = new JsonTraceBufferStore(runsDir);

    try {
      const { bundle, warning } = await buildExportBundle(runId, {
        runStore,
        failedAttemptStore,
        traceBufferStore,
      });

      if (warning !== undefined) {
        console.warn(`⚠ ${warning}`);
      }

      const target = resolveExportPath({ runId, out: opts.out, runsDir });
      const json = JSON.stringify(bundle, null, 2);
      await writeFile(target, json, 'utf8');

      const walStepCount = Object.keys(bundle.wal).length;
      console.log(
        `Exported run '${runId}' to '${target}' (${formatBytes(Buffer.byteLength(json))}).\n` +
          `  phase: ${bundle.run.run_phase}, attempts: ${bundle.attempts.length}, WAL steps: ${walStepCount}`,
      );
    } catch (err) {
      console.error(err instanceof Error ? err.message : String(err));
      process.exit(1);
    }
  });
